concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
env:
  GRADLE_OPTS: -Xmx6g -Dorg.gradle.daemon=false
  total-runners: 16
jobs:
  acceptanceTestEthereum:
    name: Acceptance Runner
    permissions:
      checks: write
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Install required packages
      run: sudo apt-get install -y xmlstarlet
    - continue-on-error: true
      name: get acceptance test report
      uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d
      with:
        branch: main
        if_no_artifact_found: true
        name: acceptance-node-\d*\d-test-results
        name_is_regexp: true
        path: tmp/junit-xml-reports-downloaded
    - continue-on-error: true
      name: setup gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      name: Split tests
      run: .github/workflows/splitTestsByTime.sh tmp/junit-xml-reports-downloaded
        ${{env.total-runners}} ${{ matrix.runner_index }} > testList.txt
    - continue-on-error: true
      if: matrix.runner_index == 0
      name: Upload Timing
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: acceptance-tests-timing
        path: tmp/timing.tsv
    - continue-on-error: true
      name: format gradle args
      run: cat testList.txt | sed -e 's/^\| / --tests /g' | tee gradleArgs.txt
    - continue-on-error: true
      name: run acceptance tests
      run: ./gradlew acceptanceTestNotPrivacy `cat gradleArgs.txt` -Dorg.gradle.parallel=true
        -Dorg.gradle.caching=true
    - continue-on-error: true
      name: cleanup tempfiles
      run: rm testList.txt gradleArgs.txt
    - continue-on-error: true
      name: Upload Acceptance Test Results
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: acceptance-node-${{matrix.runner_index}}-test-results
        path: acceptance-tests/tests/build/test-results/**/TEST-*.xml
    strategy:
      fail-fast: true
      matrix:
        runner_index:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
  accepttests-passed:
    if: always()
    name: accepttests-passed
    needs:
    - acceptanceTestEthereum
    permissions:
      checks: write
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: "${{\n  contains(needs.*.result, 'failure')\n  || contains(needs.*.result,\
        \ 'cancelled')\n  || contains(needs.*.result, 'skipped')\n}}"
      name: Fail on workflow error
      run: exit 1
name: acceptance-tests
on:
  repository_dispatch:
    types: trigger-ga___acceptance-tests.yml
