env:
  GRADLE_OPTS: -Dorg.gradle.parallel=true -Dorg.gradle.caching=true
jobs:
  artifactoryPublish:
    needs: artifacts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: setup gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      env:
        ARTIFACTORY_KEY: ${{ secrets.BESU_ARTIFACTORY_TOKEN }}
        ARTIFACTORY_USER: ${{ secrets.BESU_ARTIFACTORY_USER }}
      name: Artifactory Publish
      run: ./gradlew -Prelease.releaseVersion=${{ github.event.release.name }} -Pversion=${{github.event.release.name}}
        artifactoryPublish
  artifacts:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: setup gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      name: assemble release
      run: ./gradlew -Prelease.releaseVersion=${{github.event.release.name}} -Pversion=${{github.event.release.name}}
        assemble
    - continue-on-error: true
      id: hashes
      name: hashes
      run: 'cd build/distributions

        echo "zipSha=$(shasum -a 256 besu*.zip)" >> $GITHUB_OUTPUT

        echo "tarSha=$(shasum -a 256 besu*.tar.gz)" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: upload tarball
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        compression-level: 0
        name: besu-${{ github.event.release.name }}.tar.gz
        path: build/distributions/besu*.tar.gz
    - continue-on-error: true
      name: upload zipfile
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        compression-level: 0
        name: besu-${{ github.event.release.name }}.zip
        path: build/distributions/besu*.zip
  publish:
    needs: testWindows
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download archives
      uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe
      with:
        merge-multiple: true
        path: build/distributions
        pattern: besu-*
    - continue-on-error: true
      name: Upload Release assets
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      with:
        append_body: true
        body: '${{steps.hashes.outputs.tarSha}}

          ${{steps.hashes.outputs.zipSha}}

          '
        files: 'build/distributions/besu*.tar.gz

          build/distributions/besu*.zip

          '
  testWindows:
    needs: artifacts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      name: Download zip
      uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe
      with:
        merge-multiple: true
        pattern: besu-*.zip
    - continue-on-error: true
      name: test Besu
      run: 'dir

        unzip besu-*.zip -d besu-tmp

        cd besu-tmp

        mv besu-* ../besu

        cd ..

        besu\bin\besu.bat --help

        besu\bin\besu.bat --version

        '
    timeout-minutes: 10
name: release artifacts
on:
  repository_dispatch:
    types: trigger-ga___artifacts.yml
