env:
  registry: docker.io
jobs:
  amendNotes:
    needs: multiArch
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: add pull command to release notes
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      with:
        append_body: true
        body: '`docker pull ${{env.registry}}/${{secrets.DOCKER_ORG}}/besu:${{github.event.release.name}}`

          '
  buildDocker:
    needs: hadolint
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: prep
      name: Prepare
      run: "platform=${{ matrix.platform }}\nif [ \"$platform\" = 'ubuntu-22.04' ];\
        \ then \n  echo \"PLATFORM_PAIR=linux-amd64\" >> $GITHUB_OUTPUT\n  echo \"\
        ARCH=amd64\" >> $GITHUB_OUTPUT\nelse\n  echo \"PLATFORM_PAIR=linux-arm64\"\
        \ >> $GITHUB_OUTPUT\n  echo \"ARCH=arm64\" >> $GITHUB_OUTPUT\nfi\n"
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      id: shortSha
      name: short sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: setup gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      name: install goss
      run: 'mkdir -p docker/reports

        curl -L https://github.com/aelsabbahy/goss/releases/download/v0.4.4/goss-${{
        steps.prep.outputs.PLATFORM_PAIR }} -o ./docker/tests/goss-${{ steps.prep.outputs.PLATFORM_PAIR
        }}

        '
    - continue-on-error: true
      name: login to ${{ env.registry }}
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with:
        password: ${{ secrets.DOCKER_PASSWORD_RW }}
        registry: ${{ env.registry }}
        username: ${{ secrets.DOCKER_USER_RW }}
    - continue-on-error: true
      env:
        architecture: ${{ steps.prep.outputs.ARCH }}
      name: build and test docker
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        arguments: testDocker -PdockerOrgName=${{ env.registry }}/${{ secrets.DOCKER_ORG
          }} -Pversion=${{github.event.release.name}} -Prelease.releaseVersion=${{
          github.event.release.name }}
        cache-disabled: true
    - continue-on-error: true
      env:
        architecture: ${{ steps.prep.outputs.ARCH }}
      name: publish
      run: ./gradlew --no-daemon dockerUpload -PdockerOrgName=${{ env.registry }}/${{
        secrets.DOCKER_ORG }} -Pversion=${{github.event.release.name}} -Prelease.releaseVersion=${{
        github.event.release.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-22.04
        - - self-hosted
          - ARM64
  hadolint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: setup gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      name: hadoLint
      run: docker run --rm -i hadolint/hadolint < docker/Dockerfile
  multiArch:
    needs: buildDocker
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: setup gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      name: login to ${{ env.registry }}
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with:
        password: ${{ secrets.DOCKER_PASSWORD_RW }}
        registry: ${{ env.registry }}
        username: ${{ secrets.DOCKER_USER_RW }}
    - continue-on-error: true
      name: multi-arch docker
      run: ./gradlew manifestDocker -PdockerOrgName=${{ env.registry }}/${{ secrets.DOCKER_ORG
        }} -Pversion=${{github.event.release.name}} -Prelease.releaseVersion=${{ github.event.release.name
        }}
name: docker
on:
  repository_dispatch:
    types: trigger-ga___docker.yml
