concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
env:
  GRADLE_OPTS: -Xmx6g -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true
jobs:
  compile:
    needs:
    - spotless
    - gradle-wrapper
    - repolint
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      name: Gradle Compile
      run: ./gradlew build -x test -x spotlessCheck
    timeout-minutes: 30
  gradle-wrapper:
    name: Gradle Wrapper Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
  repolint:
    container: ghcr.io/todogroup/repolinter:v0.11.2
    name: Repository Linting
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - continue-on-error: true
      name: Lint Repo
      run: bundle exec /app/bin/repolinter.js --rulesetUrl https://raw.githubusercontent.com/hyperledger-labs/hyperledger-community-management-tools/main/repo_structure/repolint.json
        --format markdown
  spotless:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      name: run spotless
      run: ./gradlew spotlessCheck
  unitTests:
    env:
      GRADLEW_UNIT_TEST_ARGS: ${{matrix.gradle_args}}
    needs:
    - compile
    permissions:
      checks: write
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      id: unitTest
      name: run unit tests
      run: ./gradlew $GRADLEW_UNIT_TEST_ARGS
    - continue-on-error: true
      name: Upload Unit Test Results
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: unit-${{matrix.filename}}-test-results
        path: '**/test-results/**/TEST-*.xml'
    strategy:
      fail-fast: true
      matrix:
        gradle_args:
        - test -x besu:test -x consensus:test -x crypto:test -x ethereum:eth:test
          -x ethereum:api:test -x ethereum:core:test
        - besu:test consensus:test crypto:test
        - ethereum:api:testBonsai
        - ethereum:api:testForest
        - ethereum:api:testRemainder
        - ethereum:eth:test
        - ethereum:core:test
        include:
        - filename: everythingElse
          gradle_args: test -x besu:test -x consensus:test -x crypto:test -x ethereum:eth:test
            -x ethereum:api:test -x ethereum:core:test
        - filename: consensusCrypto
          gradle_args: besu:test consensus:test crypto:test
        - filename: apiBonsai
          gradle_args: ethereum:api:testBonsai
        - filename: apiForest
          gradle_args: ethereum:api:testRemainder
        - filename: apiRemainder
          gradle_args: ethereum:api:testRemainder
        - filename: eth
          gradle_args: ethereum:eth:test
        - filename: core
          gradle_args: ethereum:core:test
  unittests-passed:
    if: always()
    name: unittests-passed
    needs:
    - unitTests
    permissions:
      checks: write
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: "${{\n  contains(needs.*.result, 'failure')\n  || contains(needs.*.result,\
        \ 'cancelled')\n  || contains(needs.*.result, 'skipped')\n}}"
      name: Fail on workflow error
      run: exit 1
name: pre-review
on:
  repository_dispatch:
    types: trigger-ga___pre-review.yml
