env:
  registry: docker.io
jobs:
  dockerPromoteX64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: login to ${{ env.registry }}
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with:
        password: ${{ secrets.DOCKER_PASSWORD_RW }}
        registry: ${{ env.registry }}
        username: ${{ secrets.DOCKER_USER_RW }}
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      name: Docker upload
      run: ./gradlew "-Prelease.releaseVersion=${{ github.event.release.name }}" "-PdockerOrgName=${{
        env.registry }}/${{ secrets.DOCKER_ORG }}" dockerUploadRelease
    - continue-on-error: true
      name: Docker manifest
      run: ./gradlew "-Prelease.releaseVersion=${{ github.event.release.name }}" "-PdockerOrgName=${{
        env.registry }}/${{ secrets.DOCKER_ORG }}" manifestDockerRelease
name: release besu
on:
  repository_dispatch:
    types: trigger-ga___release.yml
