jobs:
  Analysis:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: setup gradle
      uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
      with:
        cache-disabled: true
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
        SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Build and analyze
      run: ./gradlew build sonarqube --continue --info -Dorg.gradle.parallel=true
        -Dorg.gradle.caching=true
name: SonarCloud analysis
on:
  repository_dispatch:
    types: trigger-ga___sonarcloud.yml
permissions:
  pull-requests: read
